### PR TITLE
Typo error fix for AffectNet conversion

### PR DESCRIPTION
**Pull request by sunggukcha**
Hello @yaoing , thanks for sharing your great work. 

There are typo errors regarding AffectNet conversion. 

Regards,
Sungguk Cha

### CODE REVIEW

**Review by yaoing — APPROVED** [review]
Thanks!

**Comment by yaoing** [comment]
Why should we need to make changes to affectnet.csv?

**Comment by sunggukcha** [comment]
> Why should we need to make changes to affectnet.csv?

I replaced
AfectNet -> Affectnet.

**Comment by yaoing** [comment]
OK~

**Pull request merged**
